### ISSUE TITLE
0.8.8: Color changes affect all unlinked tokens of same actor

### ISSUE THREAD

**Issue by dineshm72** [Nazacra/hitpoint-tint#1]
In the latest release 0.8.8, when a token's color tint changes, it also changes the tint of all other unlinked tokens for the same actor.  So if you have many copies of a zombie actor, say, all the them will always have the same color tint, of whatever the most recently updated token's HP tint is.

**Comment by Nazacra** [comment]
Should hopefully be resolved for you now with the latest version. I also published a version which should properly install through FoundryVTT directly.

**Comment by dineshm72** [comment]
It is fixed, yes.  However there is something wrong with the packaging on foundry, every time you update all modules, it says that this one needs to be updated, even though the update has already happened.  I think it's a problem with the URL provided.
